### ISSUE TITLE
Ctrl+C is not handled correctly

### ISSUE THREAD

**Issue by randallreedjr** [randallreedjr/git_swap#8]
Per @wearon:
> One non-blocker bug is when I do git swap --config and then Ctrl + C to cancel that it freaks out. My expectation was git swap --config will show existing profiles too and some message/warning whether it will override or append

Originally reported here: https://github.com/randallreedjr/git_switch/issues/64

**Comment by randallreedjr** [comment]
@wearon If you upgrade to v1.1.0, you should be able to use Ctrl + C. Let me know if you still run into an issue. I'll also work on updating the language around running the `config` option to make it clearer.

**Comment by wearon** [comment]
@randallreedjr will do, thank you once again
